spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/lucia
  cloud:
    gateway:
      default-filters: 
        - TokenRelay=
      mvc:
        routes:
          - id: checkout-service
            uri: lb://checkout-service
            predicates:
              - Path=/checkout


server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
