spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: checkout-service
            uri: lb://checkout-service
            predicates:
              - Path=/checkout


server:
  port: 8083
