spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/lucia
  cloud:
    gateway:
      mvc:
        routes:
          - id: checkout-service
            uri: lb://checkout-service
            predicates:
              - Path=/checkout


server:
  port: 8083
