spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        service-id: config-service
        enabled: true
    gateway:
      mvc:
        routes:
          - id: checkout-service
            uri: lb://checkout-service
            predicates:
              - Path=/checkout


server:
  port: 8083
